# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-14 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cart_manager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart_Manager',
        ),
    ]
