# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-16 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20181116_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_total',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=100),
        ),
    ]
